// ..
import './globals.css'

import { Inter } from 'next/font/google'
import NavBar from './components/navBar/navBar'
import Footer from './components/footer/footer'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Omer Y.',
  description: 'Generated by Omer Yahya',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
    
      <link rel='icon' href='./favicon.ico'/>
      </Head>
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
        {/* <script src="https://unpkg.com/aos@next/dist/aos.js"></script> */}
        <script src="https://unpkg.com/aos@next/dist/aos.js" async></script>

      </body>
    </html>
  )
}
